# Generated by Django 5.2.6 on 2025-09-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sepatu', 'Sepatu Bola'), ('jersey', 'Jersey'), ('training', 'Celana Training'), ('jaket', 'Jaket'), ('bola', 'Bola'), ('tas', 'Tas Bola'), ('poster', 'Poster'), ('figur', 'Figur Pemain'), ('aksesoris', 'Aksesoris')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='update', max_length=20)),
                ('jumlah_keranjang', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
