# Generated by Django 5.2.6 on 2025-09-15 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sepatu', 'Sepatu Bola'), ('jersey', 'Jersey'), ('training', 'Celana Training'), ('jaket', 'Jaket'), ('bola', 'Bola'), ('tas', 'Tas Bola'), ('poster', 'Poster'), ('figur', 'Figur Pemain'), ('aksesoris', 'Aksesoris')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='update', max_length=20)),
                ('items_views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
