# Generated by Django 5.2.6 on 2025-09-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_items_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('sepatu', 'Sepatu Bola'), ('jersey', 'Baju Jersey'), ('training', 'Celana Training'), ('jaket', 'Jaket'), ('bola', 'Bola'), ('tas', 'Tas Bola'), ('poster', 'Poster'), ('figur', 'Figur Pemain'), ('aksesoris', 'Aksesoris')], default='update', max_length=20),
        ),
    ]
