# Generated by Django 5.2.6 on 2025-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('sepatu', 'Sepatu Bola'), ('jersey', 'Baju Jersey'), ('jaket', 'Jaket'), ('bola', 'Bola'), ('poster', 'Poster'), ('figur', 'Figur Pemain')], default='update', max_length=20),
        ),
    ]
